### ISSUE TITLE
NameError: name 'LlavaMixtralForCausalLM' is not defined

### ISSUE THREAD

**Issue by junleiz** [SHI-Labs/CuMo#1]
Traceback (most recent call last):
  File "/data/users/zhangjunlei/anaconda3/envs/webagent/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/users/zhangjunlei/anaconda3/envs/webagent/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/users/zhangjunlei/download/install/CuMo/cumo/serve/cli.py", line 112, in <module>
    main(args)
  File "/data/users/zhangjunlei/download/install/CuMo/cumo/serve/cli.py", line 32, in main
    tokenizer, model, image_processor, context_len = load_pretrained_model(args.model_path, args.model_base, model_name, args.load_8bit, args.load_4bit, device=args.device)
  File "/data/users/zhangjunlei/download/install/CuMo/cumo/model/builder.py", line 118, in load_pretrained_model
    model = LlavaMixtralForCausalLM.from_pretrained(
NameError: name 'LlavaMixtralForCausalLM' is not defined

**Comment by makemecker** [comment]
Hello!

I am facing the same error when running the command to pre-train the MLP connector ([getting_started.md](https://github.com/SHI-Labs/CuMo/blob/main/docs/getting_started.md)):

`bash scripts/cumo/mistral_7b/pretrain_mistral_7b.sh`

I tried adding the line to the script `scripts/cumo/mistral_7b/pretrain_mistral_7b.sh`:

`from llava.model.language_model.llava_mistral import LlavaMistralForCausalLM`

However, this led to an error:

`ImportError: cannot import name 'LlavaLlamaForCausalLM' from 'llava.model' (/home/tyugunov/modules/llava/llava/model/__init__.py)`

@leoozy, could you please share how you resolved this issue?

Thank you!
