### ISSUE TITLE
Error when loading the saved checkpoint.

### ISSUE THREAD

**Issue by Marcovaldon** [SHI-Labs/CuMo#6]
I try to train the model by scripts/cumo/mistral-7b/sft*.sh on my own dataset and save two checkpoints, then I tried to load the save checkpoint to continue training or do inference, there is an error as below. 

`
Traceback (most recent call last):
  File "cumo/train/train_mem.py", line 4, in <module>
    train(attn_implementation="flash_attention_2")
  File "/Multimodal/dongshiqi/CuMo/cumo/train/train.py", line 1082, in train
    trainer.train()
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1869, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 2772, in training_step
    loss = self.compute_loss(model, inputs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 2795, in compute_loss
    outputs = model(**inputs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/engine.py", line 1852, in forward
    loss = self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/Multimodal/dongshiqi/CuMo/cumo/model/language_model/llava_llama.py", line 74, in forward
    (
ValueError: too many values to unpack (expected 6)
`

Is there something wrong?  Can you help me?

**Comment by Marcovaldon** [comment]
问题解决了，我的模型路径中不包含'mistral'字段，因此代码是按照llava_llama来加载的，推理自然会有问题。
